apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion
  namespace: ai
  labels:
    app: stable-diffusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      labels:
        app: stable-diffusion
    spec:
      containers:
        - name: automatic1111-container
          image: universonic/stable-diffusion-webui:full
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              nvidia.com/gpu: 1
              memory: "32Gi"
              cpu: "4"
            limits:
              memory: "32Gi"
              cpu: "4"
              nvidia.com/gpu: 1
          volumeMounts:
            - name: stable-diffusion-data
              mountPath: /app/stable-diffusion-webui/inputs
              subPath: inputs
            - name: stable-diffusion-data
              mountPath: /app/stable-diffusion-webui/textual_inversion_templates
              subPath: textual_inversion_templates
            - name: stable-diffusion-data
              mountPath: /app/stable-diffusion-webui/embeddings
              subPath: embeddings
            - name: stable-diffusion-data
              mountPath: /app/stable-diffusion-webui/extensions
              subPath: extensions
            - name: stable-diffusion-data
              mountPath: /app/stable-diffusion-webui/models
              subPath: models
            - name: stable-diffusion-data
              mountPath: /app/stable-diffusion-webui/localizations
              subPath: localizations
            - name: void
              mountPath: /app/stable-diffusion-webui/outputs
      volumes:
        - name: stable-diffusion-data
          persistentVolumeClaim:
            claimName: stable-diffusion-model-store
        - name: void
          emptyDir: {}
      nodeSelector:
        nvidia.com/gpu.present: "true"
