---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stable-diffusion-model-store-pv
  namespace: ollama
  labels:
    app: stable-diffusion
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/local-storage/stable-diffusion-models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8-worker-4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stable-diffusion-model-output-pv
  namespace: ollama
  labels:
    app: stable-diffusion
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/local-storage/stable-diffusion-outputs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8-worker-4
