---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-model-store
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: local-storage
