---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-model-store
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
