apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui-app
  namespace: argocd
spec:
  project: default
  source:
    chart: open-webui
    repoURL: https://open-webui.github.io/helm-charts
    targetRevision: 5.4.0
    helm:
      releaseName: my-openwebui
      valuesObject:
        ingress:
          enabled: true
          class: haproxy
          host: ai.nexus-core.dev
          tls: true
        ollama:
          enabled: false
        persistence:
          size: 15Gi
          storageClass: nfs-client
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
