apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.plane.so/
      chart: plane-ce
      targetRevision: 1.2.2
      helm:
        releaseName: my-plane
        valuesObject:
          planeVersion: stable
          ingress:
            enabled: false
          redis:
            storageClass: "longhorn"
          postgres:
            storageClass: "longhorn"
          minio:
            storageClass: "longhorn"
          rabbitmq:
            storageClass: "longhorn"
    - repoURL: https://github.com/011000100110111101101111/homelab
      path: app-in-apps/yaml/plane
      targetRevision: main
      directory:
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
