---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ingress
  namespace: adguard
  labels:
    app: adguard
  annotations:
    kubernetes.io/ingress.class: tailscale
spec:
  ingressClassName: tailscale
  rules:
    - host: adguard.border-orfe.ts.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: adguard-service-ingress
                port:
                  name: adminpanel
  tls:
    - hosts:
        - adguard.border-orfe.ts.net
