---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-workdir-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
