---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxreverseproxy-data-pvc
  namespace: nginxreverseproxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
