---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: database
spec:
  encryptedData:
    postgres-password: AgAjFgihPy3LqAeI37BNi20SAij4fEMw53b5sbVCioPVe8cIxv3Xh6Myi5jb2LpxHhW9o98Nkv6Y4FolCrVHnA+B3vd69K2bFs98hCy2AOUE46fTTV+xHsQ7Mc2sCc6hX+aXTLrKwgLXa4V9DkoJT8D7TCcfjsp9w7KHUVM4eE+nzUp6guFw64g5dhpUcBFzsKN/dJb3e0mxCfSPnh6+TYYXh/sjDm7EqJuBO8jaAzb3o7V9JU+k08cU0fVoE71fvVKtzOFHMtpHVRom0exdXdPUVVeLtjKJS8OHtUw60kCN333oJKCPkU9MC4g73ECH5roZloCcGgfsxuM3NPvlnUVlrVx671jF70PsP9VuyqqBa+i+HWMFEmERW6vYVpYgich8S4truBW0dE41SKrssxzbkJsiUtyBNbKizEQSH5FA6CmFqwbMrMIO2bL7cu/rc7tYo0dhXEbNgXfF551JW96gC1VJfEcG6LlFjWQ/l7t70B96FwVp3PAZvZ8sCLmzqxwb+a/Q9cMOr7m7KRpyYJqZzFYyYvLPTL5J58lWrAwjEcrjTjaPt068RWun0mgPMWTUMsFMla9cUkO1CHpDYvWAnAmFZL5ph+704D/Ba5tiv9ps31X/F7CqfN8XzjKr8jMzV6oh9Zk62Ragta94bVNTqiwET536f9nX2LoGNzmnNXLiU5nV83oRGWrcjQAYUGLHEjYsGB5CetKg06Ka4ksTIBHaOED/RYCJu44ESIk/hYSz/xa1YuCt
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: database
