---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgres-credentials
  namespace: gitlab
spec:
  encryptedData:
    postgres-password: AgAwOmQ22PGo7NtjGmXiUXMcLA2UH+jOOoTk/SBBzpNCy1wUpkHoqEjuex2/se0enBYDuq7IRGQmWw35ux5AsDI0N2Uvw96LNUZB5+yMdG9cmajmj4T8IGlkFBbyjzCz7S1cvIrAk3TrVmqbqONGUUGJBGJX8Ppj4hV3Dvb9L7YAw4V9PqBstZmy95tfjq5Dr3c0MnWjuXOFmURd52xXkDMegszHLjQYBOQAwjM1dL7B+TxWhX++GXJjXUg0tQrvYueYwZDJ01UXRKlyfMk7BqufERzxsYaBDs00IDAfAh79jz62vhAZVtIXUt1wiSTFB1i7hClQKPs0263BaCS4LIv43MSqHDj+8U4JaOdU8BH0ywnoantcp05XU3xQwwqVsbnM0CejGwLTXjn7tl5uyAvqJsomgFwt9PYki8nQ8CE5hL7RSMlGTZA76PL8oVHHKqGT/W21jg/LQwSFDlMscSJ3WJ3CTAOtF0KbrmYxSNmTE16LFs22M1o/qVex+Go17Qh15BId1tYCRiXlQygAEaHiYzaROrIuxNZf/zJfc7hzcdbXkloDWOrDofEFB26Rbr06Q33Si51yc2+vwhcOEoujKB8ViuAYBY+C8syXmlWNui3VzG3z1x9V2R28C+PyQbXSS4VfkL3+tjWRIxNQREn/7xu258iuz5eC0sssCWpGVhVU0xEoVD/l7FPFUv83LwUpn+bOclLUMiUBVCkEzPd5LtzYT3kVeTW8Eu7b5WRYcEiXK/Ugx/w9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-credentials
      namespace: gitlab
    type: Opaque
