apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql-mealie
  namespace: database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClassName: nfs-client
  postgresVersion: 16
  auth:
    username: mealie
    passwordSecret:
      name: postgres-credentials
      key: postgres-password
  database: mealie