apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql-mealie
  namespace: database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClassName: nfs-client
  managed:
    roles:
      - name: mealie
        ensure: present
        login: true
        passwordSecret:
          name: postgres-credentials
          key: postgres-password