---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-deployment
  labels:
    app: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.4.2
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "1"
          env:
            - name: TZ
              value: "US/Eastern"
            - name: ALLOW_SIGNUP
              value: "True"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MAX_WORKERS
              value: "1"
            - name: WEB_CONCURRENCY
              value: "1"
            - name: BASE_URL
              value: "https://mealie.nexus-core.org"
            - name: DB_ENGINE
              value: "postgres"
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-postgres-credentials
                  key: password
            - name: POSTGRES_SERVER
              value: "my-postgresql-mealie-rw.database.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "mealie"
          volumeMounts:
            - name: mealie-data
              mountPath: "/app/data"
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
