apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-app
  namespace: argocd
spec:
  project: default
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2.1.0
    helm:
      releaseName: my-authentik
      valuesObject:
        authentik:
          error_reporting:
            enabled: false

        server:
          extraEnvFrom:
            - secretRef:
                name: authentik-env-secrets
          ingress:
            enabled: true
            https: true
            ingressClassName: haproxy
            hosts:
              - authentik.nexus-core.dev
            tls:
              - secretName: authentik-server-tls
                hosts:
                  - authentik.nexus-core.dev

        worker:
          extraEnvFrom:
            - secretRef:
                name: authentik-env-secrets

        postgresql:
          enabled: true
          auth:
            existingSecret: authentik-env-secrets
            # Map the chart's expected key names to your existing ones
            passwordKey: AUTHENTIK_POSTGRESQL__PASSWORD
            postgresPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
            replicationPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

        redis:
          enabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false