apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.coder.com/v2
      chart: coder
      targetRevision: 2.26.0
      helm:
        releaseName: my-coder
        valuesObject:
          coder:
            env:
              - name: CODER_ACCESS_URL
                value: "https://coder.nexus-core.dev"
              - name: CODER_PG_CONNECTION_URL
                valueFrom:
                  secretKeyRef:
                    name: coder-db-url
                    key: url
            ingress:
              enable: false
            service:
              enable: true
              type: ClusterIP
    - repoURL: https://github.com/011000100110111101101111/homelab
      path: app-in-apps/yaml/coder
      targetRevision: main
      directory:
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false