apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-app
  namespace: argocd
spec:
  project: default
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: 8.8.1
    helm:
      releaseName: my-gitlab
      valuesObject:
        global:
          time_zone: America/New_York
          edition: ce
          hosts:
            domain: nexus-core.org
            https: true
          psql:
            host: hostname
            username: gitlab
            database: gitlab
            password:
              useSecret: true
              secret: my-gitlab-postgresql-password
              key: ppostgresql-postgres-password
          ingress:
            configureCertmanager: false
            class: haproxy
            annotations:
              kubernetes.io/ingress.class: haproxy
              cert-manager.io/cluster-issuer: homelab-issuer
            tls:
              enabled: true
        gitlab:
          webservice:
            ingress:
              enabled: true
              tls:
                - secretName: gitlab-ingress-secret
        registry:
          ingress:
            enabled: true
            tls:
              - secretName: registry-ingress-secret
        minio:
          ingress:
            enabled: true
            tls:
              - secretName: minio-ingress-secret
        certmanager:
          install: false
        nginx-ingress:
          enabled: false
        # Disable prometheus from being deployed, we have our own
        prometheus:
          install: false
        #redis:
        #  install: false
        # Disable postgresql from being deployed, we have our own
        postgresql:
          install: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
