apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.8.2
    helm:
      releaseName: my-grafana
      valuesObject:
        persistence:
          enabled: true
        dashboards:
          default:
            prometheus-stats:
              gnetId: 315
              revision: 3
              datasource: Prometheus
        ingress:
          enabled: true
          ingressClassName: tailscale
          hosts:
            - grafana.border-orfe.ts.net
          tls:
            - secretName: grafana-tls-secret
              hosts:
                - grafana.border-orfe.ts.net
        service:
          type: ClusterIP
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
