apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-operator-app
  namespace: argocd
spec:
  project: default
  source:
    chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: 24.9.1
    helm:
      releaseName: my-nvidia
      valuesObject:
        driver:
          enabled: false
        toolkit:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
