apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://otwld.github.io/ollama-helm/
      chart: ollama
      targetRevision: 1.4.0
      helm:
        releaseName: my-ollama
        valuesObject:
          ollama:
            gpu:
              enabled: true
              type: nvidia
              number: 1
            models:
              pull:
                - llama2
    - repoURL: https://github.com/011000100110111101101111/homelab
      path: app-in-apps/yaml/ollama
      targetRevision: main
      directory:
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
