apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui-app
  namespace: argocd
spec:
  project: default
  source:
    chart: open-webui
    repoURL: https://open-webui.github.io/helm-charts
    targetRevision: 5.4.0
    helm:
      releaseName: my-openwebui
      valuesObject:
        ingress:
          enabled: true
          class: tailscale
          host: ai.border-orfe.ts.net
          tls: true
        ollama:
          enabled: false
        persistence:
          size: 20Gi
          storageClass: longhorn
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
