---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-database-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami/
      chart: postgresql
      targetRevision: 16.6.0
      helm:
        releaseName: my-postgresql
        valuesObject:
          primary:
            persistence:
              enabled: true
              storageClass: nfs-client
              size: "50Gi"
          auth:
            username: "admin"
            existingSecret: "postgres-credentials"
            secretKeys:
              userPasswordKey: "postgres-password"
            database: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
