---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-database-app
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.4.3
    helm:
      releaseName: my-postgresql
      valuesObject:
        primary:
          persistence:
            enabled: true
            storageClass: longhorn
            size: "100Gi"
        auth:
          username: "admin"
          existingSecret: "postgres-credentials"
          secretKeys:
            userPasswordKey: "postgres-password"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: database
spec:
  encryptedData:
    postgres-password: AgBvuvbEJo1O8eHsaAcAWoUataL0sxLRnvkWQnX7V4Or2gkMWWmmVBX5BLLDJwQvyNP7be7IPswC3pVG2T4qbarspJ+GjQyD86d8ITiSkZ+DJLcbO8q5btyiNlNT4JhQKtwUTN+UgBpnTO4QgULSAT3EZOv3L9XQqXQh9lMXoqP2n2dD8wlkgVPgsqteqtbh1/JpYV7CVe63eiieQgVCHOlrMMylNG+/O/RPa8BPxNenmyktll6+CwzTGxcVxYGC4PUBu8TxRI1dxwa5YmD4xEvpkRYuNor+I4CH6Fi1C7iiK2eTJNWhnExApKuTV/fhZRoS7rLHqD0vGY4oqqWyPpjjHfpju3n3ZQMLQ8IEW3mKzDIM5thduT7UCk09tb6IKZlRw4hb7ziL4rUyqA4945nMrg9rRoKUZgMHmnbQ2mFRva61oO9rp3GfbBUBvNA+wTKLGejHzRxYeMFs+8Bo6HvmxB2IHXkEFynD0UBkocW5dklzHCyw2IEjE9jB/FZD8vGpzx8zZ91rHrQIUPTzxXp2yiABvnJivWQRW1u0tqpbLM6T72KwJesVaGty6pePN0hIKaPrNiq54jlntzZTulXXH25IlPJBGQehymL+7jSAkg11bMRl5odypAE2jDGo4pwpv6rI7bGutOvBggiOiBZd4Rbcm8aTQvXTDJFlYOgh7hKNyIBvQZ8ASpv/wA37kXFITl6MkQbFbD3owpuU8SPgZX5iCw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: database
