---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-database-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami/
      chart: postgresql
      targetRevision: 16.3.5
      helm:
        releaseName: my-postgresql
        valuesObject:
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: "100Gi"
          auth:
            username: "admin"
            existingSecret: "postgres-credentials"
            secretKeys:
              userPasswordKey: "postgres-password"
            database: "default"
    - repoURL: https://github.com/011000100110111101101111/homelab
      path: app-in-apps/yaml/postgres
      targetRevision: main
      directory:
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
