apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-community
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 26.0.1
    helm:
      releaseName: my-prometheus
      valuesObject:
        networkPolicy:
          enabled: true
        server:
          ingress:
            enabled: true
            hosts:
              - prometheus.border-orfe.ts.net
            path: /prometheus
            pathType: Prefix
            ingressClassName: tailscale
            service:
              type: ClusterIP
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
