apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator-app
  namespace: argocd
spec:
  project: default
  source:
    chart: vault-secrets-operator
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.10.0
    helm:
      releaseName: my-vault-secrets-operator
      valuesObject:
        defaultVaultConnection:
          enabled: true
          address: "http://my-vault.vault.svc.cluster.local:8200"
          skipTLSVerify: false
        defaultAuthMethod:
          enabled: true
          kubernetes:
            role: my-vault-role
            serviceAccount: default
            tokenAudiences:
            - vault
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
