apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wger-app
  namespace: argocd
spec:
  project: default
  source:
    chart: wger
    repoURL: https://wger-project.github.io/helm-charts
    targetRevision: 0.2.4
    helm:
      releaseName: my-wger
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: "haproxy"              # or whatever ingress class you use
          url: "wger.nexus-core.dev"
          tls: true
          annotations:
            kubernetes.io/ingress.class: haproxy
            cert-manager.io/cluster-issuer: homelab-issuer
        app:
          persistence:
            enabled: true
            storageClass: nfs-client
            size: 10Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false
