---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-deployment
  labels:
    app: placeholder
  namespace: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: placeholder
          image: placeholder/placeholderhome
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1"
          ports:
            - containerPort: 53
            - containerPort: 3000
          volumeMounts:
            - name: placeholder-workdir
              mountPath: "/opt/placeholderhome/work"
            - name: placeholder-configdir
              mountPath: "/opt/placeholderhome/conf"
      volumes:
        - name: placeholder-workdir
          persistentVolumeClaim:
            claimName: placeholder-workdir-pvc
        - name: placeholder-configdir
          persistentVolumeClaim:
            claimName: placeholder-configdir-pvc
