---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: template-workdir-pvc
  namespace: template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
