---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: placeholder-workdir-pvc
  namespace: placeholder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
