---
apiVersion: v1
kind: Service
metadata:
  name: placeholder-service-ingress
  labels:
    app: placeholder
  namespace: placeholder
spec:
  selector:
    app: placeholder
  ports:
    - name: adminpanel
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: ClusterIP
