apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
  labels:
    app: simple-nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-nginx-service
  namespace: nginx
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: simple-nginx
  type: ClusterIP
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress
#   namespace: nginx
# spec:
#   defaultBackend:
#     service:
#       name: simple-nginx-service
#       port:
#         name: https
#   ingressClassName: tailscale
#   tls:
#     - hosts:
#         - nginx

