---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-gitlab-gitlab-initial-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgA3gn6jBx0WWYAXQntBbWcODUcDFlyeYQ3rwxyAc41DGZBIN62LKhGOrF//1as+4xz4YtPWX1k7BCWSDFMFDoSwK7qUpT6cYbwsvqOQEwvj9y0zFoMGl1g3Hu/ghM+xs+xCk4n0K9ob2Fiu6vKRTr8XbEVLam1GCnwpA667NBnFhQFrG1gjQPH+bPxDzu6fsHm30iXxJCCzAwA88x9aR/k+Z6SXxzb5biwm+jhtfoiMuQ7rjdvIz7Xa8t/UEVCAHISbSBFmfA0DFccP2TxRJwVePgykOOEKKecdsI4q51zd5R5gjZqSXW4fM+IIuaifbtvMj1QZZc0+okCWx5YbNwu7SJYCcOXuyA4F5GPEtlCZpkrOb88GVt5jyebWgvUBFwM43rSw4qVOybhch4sMu7S5YsrBNcPi1LKLvFgmwe9dzeJP4hopL2vzn/my9UL6+GU2v0zKNDDAWIZ7QIntTQeoiPdUbkL4pB1YPJy4ZasRQBcC93SfgBrbyDNzXvVfUsWXmkDxXWEEk2Nmz1iNOfFbk6XtfWp0GBUJn1AWYPfocVeiY4n+EgRT6w9pgxPdslkWz06NpTk4cLi2inGSRHtgqPTSgMAVg+ARBtrfXT0nV2HMjXRNLEVWmRPOHfeFkyQskpvfbM/2e0oWuLXM3xFXw49dJrl/+0L/IwRE/YNFhq4JsLZrNMPM9Ia05+YmfCuRtRpN4e/xXCIsHP3zJA4ZxG9SIZA4dmRj6QJgdxlt4j2zHtEJVCez
  template:
    metadata:
      creationTimestamp: null
      name: my-gitlab-gitlab-initial-root-password
      namespace: gitlab
