---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: my-gitlab-postgresql-password
  namespace: gitlab
spec:
  encryptedData:
    postgresql-postgres-password: AgABVgaBTlIg9w1VFXBEKA2VgxMWZKeb/GfoQ4XoXRcp5G0vk6gBlnY5VeujnenBIH8XnUHVQQAq3oL04RayEXoVYcdAuGm8FRo7ho5H/RN/NIvLfXeQcJHgduutQ6oJvDpK/SlX2NfOa857w38/OyoTbGdemfjweazIhtKt5aIF7OGdyzsGwd4nmh85hfz535nZ9p3G+sL+/jltv9856ta1/vR/EFUl60yEFZTf7Beru9VoGfHEJNVc+7X2P2b9RwIcElqttaU2QOp+KThSBrfJSr/51E4zLtYPlQGbbGc7WI4n676m2xp7bDVCRxLedy6TzIVPrNoA7buRLl37S1Ofq1zn/HHqtfC6gMkAAs4n7HMq7Zw3CJk8BsBRp5CvZkY4UyFPlnylIBzQmUN+tk6Gp9V+BCDVFBdYXFSIInT6ImwKptTLwgXmfnUkxEtMEdl8vLVp2uMJxDXhlpkH8C1lG8aS1CnPOW57kBXr/34W72rxrVN0qIYFE/dj6u+loUCvwQol3sVOCUtQRk725vXO98EHWLPNsZ53uJtIHUIUDGKC8BlgXGlH+j6bC1rHBxK1IZRhCvdnR8ES6SoZpkE33QTRJXER15/z9kM8qByz12bhhBtFCG+vvl0A9u+P6oNYpIPYSF8Dd5V490cfAGVoM+arMkAbYftLZs30/IysF3owly4wQSlvrB8g9kfNs3wQb8uRDwzqkY2tMC9LWRE2lCKSzyfD/Ufc0iVOZRLUMTQ0qjKROKq4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: my-gitlab-postgresql-password
      namespace: gitlab
    type: Opaque
