---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-data-pvc
  namespace: nocodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
