---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Home
    headerStyle: clean
    background:
      image: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
      blur: md
      saturate: 50
      brightness: 50
      opacity: 70
    theme: dark
    color: zinc
    useEqualHeights: false
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    hideVersion: true
    hideErrors: true
    statusStyle: "dot"
    layout:
      FavSites:
        iconsOnly: true
        header: false
        style: row
      Arr:
        header: false
        style: row
        columns: 3
      Platform:
        header: false
        style: row
        columns: 3
        Media:
          header: false
          style: row
          Apps:
            header: false
            style: row
            columns: 2
        NAS:
          header: false
          style: row
        Calendar:
          header: false
          style: row

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |

  services.yaml: |
    - Platform:
      - Media:
        - Portainer:
            icon: portainer.png
            href: https://portainer.nexus-core.org
            description: Docker container management
            siteMonitor: https://portainer.nexus-core.org
            widget:
              type: portainer
              url: https://portainer.nexus-core.org
              env: 3
              key: {{HOMEPAGE_VAR_PORTAINER-KEY}}
              fields: ["running","stopped"]
        - Proxy Manager:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nginx-proxy-manager.png
            href: https://nginxreverseproxy.nexus-core.dev
            description: Certificate Management
            siteMonitor: https://nginxreverseproxy.nexus-core.dev
        - Network:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/ubiquiti-unifi.png
            href: https://network.nexus-core.org/
            description: Network Control
            siteMonitor: https://network.nexus-core.org/
        - UNAS Pro:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/ugreen-nas.png
            href: https://drive.nexus-core.org/
            description: Primary NAS
            siteMonitor: https://drive.nexus-core.org/
        - Apps:

      - NAS:

      - Calendar:
        - " ":
            widget:
              type: calendar
              firstDayInWeek: sunday
              view: monthly
              showTime: true
              timezone: America/New_York
              integrations:
                - type: sonarr
                  service_group: Arr
                  service_name: Sonarr
                  color: blue
                  params:
                    unmonitored: false
                - type: radarr
                  service_group: Arr
                  service_name: Radarr
                  color: yellow
                  params:
                    unmonitored: false
                - type: lidarr
                  service_group: Arr
                  service_name: Lidarr
                  color: green
                  params:
                    unmonitored: false
    - Arr:
      - Qbit:
          icon: qbittorrent.png
          href: http://192.168.10.50:8200
          description: Bittorrent management
          siteMonitor: http://192.168.10.50:8200
          widget:
            type: qbittorrent
            url: http://192.168.10.50:8200
            username: admin
            password: {{HOMEPAGE_VAR_QBIT}}
      - Radarr:
          icon: radarr.png
          href: https://radarr.nexus-core.org
          description: Movie management
          siteMonitor: https://radarr.nexus-core.org
          widget:
            type: radarr
            url: https://radarr.nexus-core.org
            key: {{HOMEPAGE_VAR_RADARR}}
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.nexus-core.org
          description: TV series management
          siteMonitor: https://sonarr.nexus-core.org
          widget:
            type: sonarr
            url: https://sonarr.nexus-core.org
            key: {{HOMEPAGE_VAR_SONARR}}
      - Lidarr:
          icon: lidarr.png
          href: https://lidarr.nexus-core.org
          description: Music management
          siteMonitor: https://lidarr.nexus-core.org
          widget:
            type: lidarr
            url: https://lidarr.nexus-core.org
            key: {{HOMEPAGE_VAR_LIDARR}}
      - Prowlarr:
          icon: prowlarr.png
          href: https://prowlarr.nexus-core.org
          description: Indexer management
          siteMonitor: https://prowlarr.nexus-core.org
          widget:
            type: prowlarr
            url: https://prowlarr.nexus-core.org
            key: {{HOMEPAGE_VAR_PROWLARR}}
            fields: ["numberOfGrabs","numberOfQueries"]
      - Jellyfin:
          icon: jellyfin.png
          href: https://jellyfin.nexus-core.org
          description: Media center
          siteMonitor: https://jellyfin.nexus-core.org
          widgets:
            - type: jellyfin
              url: https://jellyfin.nexus-core.org
              key: {{HOMEPAGE_VAR_JELLYFIN}}
              fields: ["albums", "movies", "tv"]
      - Jellyseer:
          icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyseerr.png
          href: https://jellyseer.nexus-core.org
          description: Media discovery
          siteMonitor: https://jellyseer.nexus-core.org
          widget:
            type: jellyseerr
            url: https://jellyseer.nexus-core.org
            key: {{HOMEPAGE_VAR_JELLYSEER}}
      - Sabnzbd:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/sabnzbd.png
        href: https://sabnzbd.nexus-core.dev
        description: Usenet Downloader
        siteMonitor: https://sabnzbd.nexus-core.dev
        widget:
          type: sabnzbd
          url: https://sabnzbd.nexus-core.dev
          key: {{HOMEPAGE_VAR_SABNZBD_KEY}}
      - Adguard:
          icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
          href: https://adguard.nexus-core.dev
          description: Add Blocking
          siteMonitor: https://adguard.nexus-core.dev
          widget:
            type: adguard
            url: https://adguard.nexus-core.dev
            username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
  widgets.yaml: |
    - kubernetes:
        cluster:
          # Shows cluster-wide statistics
          show: true
          # Shows the aggregate CPU stats
          cpu: true
          # Shows the aggregate memory stats
          memory: true
          # Shows a custom label
          showLabel: true
          label: "cluster"
        nodes:
          # Shows node-specific statistics
          show: true
          # Shows the CPU for each node
          cpu: true
          # Shows the memory for each node
          memory: true
          # Shows the label, which is always the node name
          showLabel: true
    - search:
        provider: google
        target: _blank
        showSearchSuggestions: true
    - openmeteo:
        label: Boston
        latitude: 42.496691
        longitude: -70.947365
        timezone: US/Eastern
        units: imperial
        cache: 5
        format:
          maximumFractionDigits: 1
    # - datetime:
    #     text_size: xl
    #     format:
    #       timeStyle: short
    #       hourCycle: h23
    #       dateStyle: short
  docker.yaml: ""
