---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: NAS
    headerStyle: clean
    background:
      image: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
      blur: md
      saturate: 50
      brightness: 50
      opacity: 70
    theme: dark
    color: zinc
    useEqualHeights: false
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    hideVersion: true
    hideErrors: true
    statusStyle: "dot"
    layout:
      FavSites:
        iconsOnly: true
        header: false
        style: row
      Arr:
        header: false
        style: row
        columns: 5
      Platform:
        header: false
        style: row
        columns: 3
        Media:
          header: false
          style: row
          Apps:
            header: false
            style: row
            columns: 2
        NAS:
          header: false
          style: row
        Calendar:
          header: false
          style: row

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |

  services.yaml: |
    - Platform:
      - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.nexus-core.org
            description: Media center
            siteMonitor: https://jellyfin.nexus-core.org
            widgets:
              - type: jellyfin
                url: https://jellyfin.nexus-core.org
                key: {{HOMEPAGE_VAR_JELLYFIN}}
                fields: ["albums", "movies", "tv"]
        - Jellyseer:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyseerr.png
            href: https://jellyseer.nexus-core.org
            description: Media discovery
            siteMonitor: https://jellyseer.nexus-core.org
            widget:
              type: jellyseerr
              url: https://jellyseer.nexus-core.org
              key: {{HOMEPAGE_VAR_JELLYSEER}}
        - Adguard:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
            href: https://adguard.nexus-core.dev
            description: Add Blocking
            siteMonitor: https://jellyseer.nexus-core.dev
            widget:
              type: adguard
              url: https://adguard.nexus-core.dev
              username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
              password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
        - Apps:
            - Resilio Sync:
                icon: https://external-content.duckduckgo.com/ip3/help.resilio.com.ico
                href: http://{{HOMEPAGE_VAR_HOST}}:8888
                description: File synchronization
                siteMonitor: http://{{HOMEPAGE_VAR_HOST}}:8888
      - NAS:
        - SparrowNAS:
            icon: truenas-scale.png
            href: http://{{HOMEPAGE_VAR_HOST}}
            description: Primary NAS
            siteMonitor: http://{{HOMEPAGE_VAR_HOST}}
            widget:
              type: truenas
              url: http://{{HOMEPAGE_VAR_HOST}}
              key: {{HOMEPAGE_VAR_TN_PRIMARY}}
              enablePools: true
        - Portainer:
            icon: portainer.png
            href: https://{{HOMEPAGE_VAR_HOST}}:31015
            description: Docker container management
            siteMonitor: https://{{HOMEPAGE_VAR_HOST}}:31015
            widget:
              type: portainer
              url: https://{{HOMEPAGE_VAR_HOST}}:31015
              env: 3
              key: {{HOMEPAGE_VAR_PORTAINER-KEY}}
              fields: ["running","stopped"]
        - VelkaNAS:
            icon: truenas-scale.png
            href: http://{{HOMEPAGE_VAR_HOST_BACKUP}}
            description: Backup NAS
            siteMonitor: http://{{HOMEPAGE_VAR_HOST_BACKUP}}
            widget:
              type: truenas
              url: http://{{HOMEPAGE_VAR_HOST_BACKUP}}
              key: {{HOMEPAGE_VAR_TN_BACKUP}}
              enablePools: true
      - Calendar:
        - " ":
            widget:
              type: calendar
              firstDayInWeek: sunday
              view: monthly
              showTime: true
              timezone: America/New_York
              integrations:
                - type: sonarr
                  service_group: Arr
                  service_name: Sonarr
                  color: blue
                  params:
                    unmonitored: false
                - type: radarr
                  service_group: Arr
                  service_name: Radarr
                  color: yellow
                  params:
                    unmonitored: false
                - type: lidarr
                  service_group: Arr
                  service_name: Lidarr
                  color: green
                  params:
                    unmonitored: false
    - Arr:
      - Qbit:
          icon: qbittorrent.png
          href: http://192.168.10.50:8200
          description: Bittorrent management
          siteMonitor: http://192.168.10.50:8200
          widget:
            type: qbittorrent
            url: http://192.168.10.50:8200
            username: admin
            password: {{HOMEPAGE_VAR_QBIT}}
      - Radarr:
          icon: radarr.png
          href: https://radarr.nexus-core.org
          description: Movie management
          siteMonitor: https://radarr.nexus-core.org
          widget:
            type: radarr
            url: https://radarr.nexus-core.org
            key: {{HOMEPAGE_VAR_RADARR}}
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.nexus-core.org
          description: TV series management
          siteMonitor: https://sonarr.nexus-core.org
          widget:
            type: sonarr
            url: https://sonarr.nexus-core.org
            key: {{HOMEPAGE_VAR_SONARR}}
      - Lidarr:
          icon: lidarr.png
          href: https://lidarr.nexus-core.org
          description: Music management
          siteMonitor: https://lidarr.nexus-core.org
          widget:
            type: lidarr
            url: https://lidarr.nexus-core.org
            key: {{HOMEPAGE_VAR_LIDARR}}
      - Prowlarr:
          icon: prowlarr.png
          href: https://prowlarr.nexus-core.org
          description: Indexer management
          siteMonitor: https://prowlarr.nexus-core.org
          widget:
            type: prowlarr
            url: https://prowlarr.nexus-core.org
            key: {{HOMEPAGE_VAR_PROWLARR}}
            fields: ["numberOfGrabs","numberOfQueries"]
  widgets.yaml: |
    - kubernetes:
        cluster:
          # Shows cluster-wide statistics
          show: true
          # Shows the aggregate CPU stats
          cpu: true
          # Shows the aggregate memory stats
          memory: true
          # Shows a custom label
          showLabel: true
          label: "cluster"
        nodes:
          # Shows node-specific statistics
          show: true
          # Shows the CPU for each node
          cpu: true
          # Shows the memory for each node
          memory: true
          # Shows the label, which is always the node name
          showLabel: true
    - search:
        provider: google
        target: _blank
        showSearchSuggestions: true
    - openmeteo:
        label: Boston
        latitude: 42.496691
        longitude: -70.947365
        timezone: US/Eastern
        units: imperial
        cache: 5
        format:
          maximumFractionDigits: 1
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          hourCycle: h23
          dateStyle: short
  docker.yaml: ""
