apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: homepage-auth
  namespace: homepage
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: homepage
    serviceAccount: default
    audiences:
      - vault