---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
  annotations:
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: homelab-issuer
spec:
  ingressClassName: haproxy
  rules:
    - host: home.nexus-core.org
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: homepage-service
                port:
                  number: 3000
  tls:
    - hosts:
        - home.nexus-core.org
      secretName: homepage-ingress-secret
