---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bytestash-snippets-pvc
  namespace: bytestash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
