---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: walos-db-pvc
  namespace: walos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: walos-logos-pvc
  namespace: walos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
