apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql-metabase
  namespace: database
spec:
  instances: 1
  storage:
    size: 8Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: metabase
      owner: metabase
      secret:
        name: metabase-postgres-credentials