---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-workdir-pvc
  namespace: metabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
