---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperlessngx
  namespace: paperlessngx
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: paperlessngx
  template:
    metadata:
      labels:
        app: paperlessngx
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.37
        command: ['sh', '-c', 'until nc -z my-postgresql-paperlessngx-rw.database.svc.cluster.local 5432; do echo "Waiting for Postgres..."; sleep 5; done']
        imagePullPolicy: IfNotPresent
      containers:
      - name: paperlessngx
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PAPERLESS_OCR_LANGUAGE
          value: eng
        - name: PAPERLESS_REDIS
          value: redis://redis:6379
        - name: PAPERLESS_DBHOST
          value: my-postgresql-paperlessngx-rw.database.svc.cluster.local
        - name: PAPERLESS_DBNAME
          value: paperlessngx
        - name: PAPERLESS_URL
          value: https://paperless.nexus-core.dev
        - name: PAPERLESS_CSRF_TRUSTED_ORIGINS
          value: https://paperless.nexus-core.dev
        - name: PAPERLESS_DBUSER
          valueFrom:
            secretKeyRef:
              name: paperless-db-credentials
              key: username
        - name: PAPERLESS_DBPASS
          valueFrom:
            secretKeyRef:
              name: paperless-db-credentials
              key: password
        - name: PAPERLESS_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: paperlessngx-secrets
              key: PAPERLESS_ADMIN_USER
        - name: PAPERLESS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: paperlessngx-secrets
              key: PAPERLESS_ADMIN_PASSWORD
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: media
          mountPath: /usr/src/paperless/media
        - name: consume
          mountPath: /usr/src/paperless/consume
        startupProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: paperlessngx-media
      - name: consume
        persistentVolumeClaim:
          claimName: paperlessngx-consume