---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: paperlessngx
spec:
  selector:
    app: redis
  ports:
    - name: access
      port: 6379
      protocol: TCP
      targetPort: 6379
  type: ClusterIP


  apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: paperless
spec:
  ports:
  - port: 6379
  selector:
    app: redis
