apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-dbside-secrets
  namespace: database
spec:
  vaultAuthRef:
    name: paperless-auth
  mount: kv-v2
  type: kv-v2
  path: paperlessngx/db
  refreshAfter: 10s
  destination:
    create: true
    name: postgres-credentials
  rolloutRestartTargets: []