apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastefy
  labels:
    app: pastefy
  namespace: pastefy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pastefy
  template:
    metadata:
      labels:
        app: pastefy
    spec:
      containers:
        - name: pastefy
          image: interaapps/pastefy:latest
          env:
          - name: DATABASE_DRIVER
            value: mysql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: pastefy-db-credentials
                key: database_name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: pastefy-db-credentials
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pastefy-db-credentials
                key: password
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: pastefy-db-credentials
                key: database_host
          - name: SERVER_NAME
            value: https://paste.nexus-core.dev
          ports:
            - containerPort: 80



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: pastefy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pastefy-db-credentials
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pastefy-db-credentials
                  key: database_name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: pastefy-db-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pastefy-db-credentials
                  key: password
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-data