apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pastefy-db-secrets
  namespace: vault-secrets-operator
spec:
  vaultAuthRef: pastefy-db-auth
  mount: kv-v2
  type: kv-v2
  path: pastefy
  refreshAfter: 10s
  destination:
    create: true
    name: pastefy-db-credentials
    namespace: database
  rolloutRestartTargets:
  - kind: Deployment
    name: pastefy


---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pastefy-db-secrets
  namespace: vault-secrets-operator
spec:
  vaultAuthRef: pastefy-db-auth
  mount: kv-v2
  type: kv-v2
  path: pastefy
  refreshAfter: 10s
  destination:
    create: true
    name: pastefy-db-credentials
    namespace: pastefy
  rolloutRestartTargets:
  - kind: Deployment
    name: pastefy