apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pastefy-db-auth
  namespace: vault-secrets-operator
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: pastefy
    serviceAccount: my-vault-secrets-operator-controller-manager
    audiences:
      - vault

---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pastefy-db-auth
  namespace: vault-secrets-operator
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: pastefy
    serviceAccount: my-vault-secrets-operator-controller-manager
    audiences:
      - vault