apiVersion: v1
kind: PersistentVolume
metadata:
  name: koel-image_storage-pv
spec:
  capacity:
    storage: 1Ti # metadata only
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=3
    - hard
  nfs:
    server: 192.168.9.98
    path: /var/nfs/shared/MediaStorage/media/image_storage
