apiVersion: v1
kind: PersistentVolume
metadata:
  name: koel-search_indexers-pv
spec:
  capacity:
    storage: 30Gb # metadata only
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=3
    - hard
  nfs:
    server: 192.168.9.98
    path: /var/nfs/shared/MediaStorage/appdata/koel/search_indexers
