apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-search-indexers-pvc
  namespace: koel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  volumeName: koel-search-indexers-pv
  resources:
    requests:
      storage: 30Gi
