apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coder-dbside-secrets
  namespace: database
spec:
  vaultAuthRef: coder-auth-db
  mount: kv-v2
  type: kv-v2
  path: coder/db
  refreshAfter: 10s
  destination:
    create: true
    name: coder-postgres-credentials