apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coder-secrets
  namespace: coder
spec:
  mount: kv-v2
  type: kv-v2
  path: coder/db_url
  refreshAfter: 10s
  destination:
    create: true
    name: coder-db-url
  rolloutRestartTargets:
  - kind: Deployment
    name: coder

---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coder-dbside-secrets
  namespace: database
spec:
  mount: kv-v2
  type: kv-v2
  path: coder/db
  refreshAfter: 10s
  destination:
    create: true
    name: coder-postgres-credentials