apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openproject-admin-secrets
  namespace: openproject
spec:
  mount: kv-v2
  type: kv-v2
  path: openproject/admin
  refreshAfter: 10s
  destination:
    create: true
    name: openproject-admin-credentials
  rolloutRestartTargets:
    - kind: Deployment
      name: my-openproject-web

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openproject-db-secrets
  namespace: openproject
spec:
  mount: kv-v2
  type: kv-v2
  path: openproject/db
  refreshAfter: 10s
  destination:
    create: true
    name: openproject-db-credentials

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openproject-db-secrets
  namespace: database
spec:
  mount: kv-v2
  type: kv-v2
  path: openproject/db
  refreshAfter: 10s
  destination:
    create: true
    name: openproject-db-credentials
